### ISSUE TITLE
Changing Case of units, foods and keywords not possible

### ISSUE THREAD

**Issue by stewartadam** [TandoorRecipes/recipes#170]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.10.1

### Bug description
During recipe web import, changing the case of an unit (e.g. `Cups` to `cups`) causes page errors to appear on any change (i..e each keypress) in the unit field in an ingredients row. Note that this only occurs if the unit you are changing case for does not already exist in your installation.

1. Import any web recipe. The units on your ingredient row could look like this:
    ![image](https://user-images.githubusercontent.com/77808/91629059-4e782500-e97a-11ea-8c7f-8ff0d28c1a3e.png)
2. Click into one of the parsed ingredients **that does not already exist in your installation** and retype it exactly as is, but lowercase (e.g. `TBSP` to `tbsp`) and hit <enter> to submit the replacement ingredient:
    ![image](https://user-images.githubusercontent.com/77808/91629068-5f289b00-e97a-11ea-9a66-e523303a4b34.png)
3. Note the field now says "Select One":
    
![image](https://user-images.githubusercontent.com/77808/91629070-68196c80-e97a-11ea-8199-17286cce448e.png)

4. Interacting with another field or returning to edit the empty "Select One" field and retype the unit (e.g. `tbsp`) yields pop-up errors on every keypress:
    ![image](https://user-images.githubusercontent.com/77808/91628657-c2b0c980-e976-11ea-9bf9-1c657f713589.png)
5. Use the eraser button to clear the broken unit field
5. Re-enter `tbsp` into the field and hit <Enter> to accept
6. Submit the recipe, note in the `POST /data/import/url` form data that `recipeIngredient[x].unit=null`.

Actual results:
- Unit field gets into a broken state and cannot be fixed without total page refresh and losing progress editing the imported recipe
- Recipe import fails, partially importing the recipe without giving much detail to the end-user

Expected results:
- specifically: unit field can be reset to a working state by pressing erase button
- generally: changing ingredient case is a valid operation that does not produce UI errors
- failure to import recipes during web import provide some human-readable error message to the user
- specifically: import should act as an atopic operation and failure should not produce a semi-completed recipe
- generally: import should be more resilient to localized failures during ingredient row import, perhaps zero/null out that entry and carry on?

**Comment by stewartadam** [comment]
During step 2, one can observe auto-complete requests going through as one types e.g. `GET ?q=tbsp`
```
{"results": [], "pagination": {"more": false}}
```

JavaScript console produces in step 4:
```
vue.js:634 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'text' of null"

found in

---> <VueMultiselect>
       <Root>
warn @ vue.js:634
logError @ vue.js:1893
globalHandleError @ vue.js:1888
handleError @ vue.js:1848
invokeWithErrorHandling @ vue.js:1871
invoker @ vue.js:2188
invokeWithErrorHandling @ vue.js:1863
Vue.$emit @ vue.js:3889
activate @ vue-multiselect.min.js:1
toggle @ vue-multiselect.min.js:1
mousedown @ vue-multiselect.min.js:1
invokeWithErrorHandling @ vue.js:1863
invoker @ vue.js:2188
original._wrapper @ vue.js:7547

vue.js:1897 TypeError: Cannot read property 'text' of null
    at Vue.openUnitSelect (url:521)
    at invokeWithErrorHandling (vue.js:1863)
    at VueComponent.invoker (vue.js:2188)
    at invokeWithErrorHandling (vue.js:1863)
    at VueComponent.Vue.$emit (vue.js:3889)
    at VueComponent.activate (vue-multiselect.min.js:1)
    at VueComponent.toggle (vue-multiselect.min.js:1)
    at mousedown (vue-multiselect.min.js:1)
    at invokeWithErrorHandling (vue.js:1863)
    at HTMLSpanElement.invoker (vue.js:2188)
```

During step 7, the server error during POST is:
```
An error occurred while trying to import this recipe!DoesNotExist at /data/import/url Unit matching query does not exist. Request Method: POST Request URL: http://localhost:8080/data/import/url Django Version: 3.0.7 Python Executable:
...
Server time: Sat, 29 Aug 2020 06:59:33 +0200 Installed Applications: ['dal', 'dal_select2', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'django_tables2', 'django_filters', 'crispy_forms', 'emoji_picker', 'rest_framework', 'rest_framework.authtoken', 'django_cleanup.apps.CleanupConfig', 'cookbook.apps.CookbookConfig'] Installed Middleware: ['django.middleware.security.SecurityMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware'] Traceback (most recent call last): File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner response = get_response(request) File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response response = self.process_exception_by_middleware(e, request) File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view return view_func(request, *args, **kwargs) File "/opt/recipes/cookbook/views/data.py", line 127, in import_url u = Unit.objects.get(name=request.user.userpreference.default_unit) File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get raise self.model.DoesNotExist( Exception Type: DoesNotExist at /data/import/url Exception Value: Unit matching query does not exist. Request information: USER: stewartadam GET: No GET data POST: No POST data FILES: No FILES data
```

**Comment by vabene1111** [comment]
Ok this appears to be two issues.

1. Vue Multiselct (which is the lib used for the select boxes) does not allow creation of new entries (tagging) if another entry with the same text already exists (at least if the search can find it)

There are several issues related to case sensitivity 
https://github.com/shentao/vue-multiselect/issues/225 
https://github.com/shentao/vue-multiselect/issues/560

This could be fixed by making the search case sensitive but that is a bad thing in itself. Maybe there is a javascript fix for this but i don't know yet.

2. removing the unit from the select causes errors as the search cant find the text property of the selected unit when opening the search. This could be fixed.


In order to further investigate problem 1 i will leave this issue open because it not only relates to importing but also editing existing recipes to change the case of units (or foods for that matter)

**Comment by smilerz** [comment]
once #865 is merged this should be resolved

**Comment by vabene1111** [comment]
how is this resolved by #865 @smilerz ? I could already go to some edit page manually before to change the case but the problem is that `vue-multiselect` does not differentiate between capitalized and non capitalized letters or am i missing something here ?

**Comment by smilerz** [comment]
I misunderstood the issue and can be safely ignored.

**Comment by vabene1111** [comment]
haha ok perfect, i was hoping i misunderstood your code vue-multiselect does not seem all to invested in fixing this

**Comment by bee395** [comment]
I tried to reproduce this issue and it looks like it has been partially solved
Units are currently case sensitive
But Foods and Keywords are still case insensitive

**Comment by vabene1111** [comment]
interesting, will need to look into if there is a difference between those that could lead to this inconsistent behavior

**Comment by vabene1111** [comment]
library replaced in Tandoor 2
