### ISSUE TITLE
Error 500 unable to load webapp

### ISSUE THREAD

**Issue by ChrisMichl** [TandoorRecipes/recipes#4016]
### Tandoor Version

2.1.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Webapp does not start at all and shows 500 error. Switching back to 2.1.0 fixed it.

### Relevant logs

```shell
tandoor           | ::1 - - [08/Sep/2025:20:41:04 +0200] "GET / HTTP/1.0" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0"
tandoor           | 172.24.0.3 - - [08/Sep/2025:20:41:04 +0200] "GET / HTTP/1.1" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0" "xxx.xxx.xxx.xxx"
tandoor           | ThreadPoolExecutor-0_0 ERROR 2025-09-08 20:41:04,641 django.request Internal Server Error: /
tandoor           | Traceback (most recent call last):
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
tandoor           |     response = get_response(request)
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
tandoor           |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tandoor           |   File "/opt/recipes/cookbook/views/views.py", line 46, in index
tandoor           |     return render(request, 'frontend/tandoor.html', {})
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/shortcuts.py", line 24, in render
tandoor           |     content = loader.render_to_string(template_name, context, request, using=using)
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
tandoor           |     return template.render(context, request)
tandoor           |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 61, in render
tandoor           |     return self.template.render(context)
tandoor           |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 175, in render
tandoor           |     return self._render(context)
tandoor           |            ~~~~~~~~~~~~^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 167, in _render
tandoor           |     return self.nodelist.render(context)
tandoor           |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
tandoor           | ::ffff:127.0.0.1 - - [08/Sep/2025:20:41:04 +0200] "GET / HTTP/1.0" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0"
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 1005, in render
tandoor           |     return SafeString("".join([node.render_annotated(context) for node in self]))
tandoor           |                                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 966, in render_annotated
tandoor           |     return self.render(context)
tandoor           |            ~~~~~~~~~~~^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/library.py", line 237, in render
tandoor           |     output = self.func(*resolved_args, **resolved_kwargs)
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/utils/safestring.py", line 53, in wrapper
tandoor           |     return safety_marker(func(*args, **kwargs))
tandoor           |                          ~~~~^^^^^^^^^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/templatetags/django_vite.py", line 67, in vite_asset
tandoor           |     return DjangoViteAssetLoader.instance().generate_vite_asset(path, app, **kwargs)
tandoor           |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 818, in generate_vite_asset
tandoor           |     return app_client.generate_vite_asset(path, **kwargs)
tandoor           |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 331, in generate_vite_asset
tandoor           |     url = self.get_production_server_url(manifest_entry.file)
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 286, in get_production_server_url
tandoor           |     return staticfiles_storage.url(production_server_url)
tandoor           |            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
tandoor           |     return self._url(self.stored_name, name, force)
tandoor           |            ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
tandoor           |     hashed_name = hashed_name_func(*args)
tandoor           |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
tandoor           |     raise ValueError(
tandoor           |         "Missing staticfiles manifest entry for '%s'" % clean_name
tandoor           |     )
tandoor           | ValueError: Missing staticfiles manifest entry for 'vue3/assets/main-Gf0_X69P.js
```

**Comment by vabene1111** [comment]
this is very strange, seems the be the same issue that seemingly was resolved with 2.1.0 #3966 

There must be something in the build process that can cause the manifest to not correctly build but I do not understand why this only affects some people.

**Comment by vabene1111** [comment]
ok so I have reviewed the code and also the plugin that raises this issue and I am still not sure how this happens. Sadly I do not think I can find out anything else on this issue because I do not have an instance to reproduce this. 

Can you test the following for me: update to 2.1.1 again and see if the issue happens. Down and start the container again on the same version and see if it still happens (maybe repeat 1-2 times). thank you

EDIT: if anyone else has this issue, please post details about what happens for you. Also please try the down and restart.

**Comment by LittleSixfie** [comment]
Hi, I have the same error. I just started a new stack in portianer with this config as a docker compose in my nas:
` services:
  db_recipes:
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_DB=djangodb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=xxxxx
      - TZ=Europe/xxx
      - SECRET_KEY=xxx
    networks:
      - default_bridge


  web_recipes:
    restart: always
    image: vabene1111/recipes:2.1.2
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_DB=djangodb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=xxx
      - TZ=Europe/xxx
      - SECRET_KEY=xxx
    ports:
      - 12345:8080
    networks:
      - default_bridge

networks:
  default_bridge:
    external: true
    name: arroz
    
volumes:
  staticfiles:`

This is the error: 

`ThreadPoolExecutor-0_0 ERROR 2025-09-11 09:43:10,273 django.request Internal Server Error: /setup/
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cookbook_userpreference.image_id does not exist
LINE 1: SELECT "cookbook_userpreference"."user_id", "cookbook_userpr...
                                                    ^
HINT:  Perhaps you meant to reference the column "cookbook_userpreference.space_id".
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/cookbook/views/views.py", line 306, in setup
    user.save()
    ~~~~~~~~~^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/auth/base_user.py", line 76, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
    ~~~~~~~~~~~~~~^
        sender=origin,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        using=using,
        ^^^^^^^^^^^^
    )
    ^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/dispatch/dispatcher.py", line 177, in send
    (receiver, receiver(signal=self, sender=sender, **named))
               ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/cookbook/signals.py", line 40, in create_user_preference
    UserPreference.objects.get_or_create(user=instance)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ~~~~~~~~^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cookbook_userpreference.image_id does not exist
LINE 1: SELECT "cookbook_userpreference"."user_id", "cookbook_userpr...
                                                    ^
HINT:  Perhaps you meant to reference the column "cookbook_userpreference.space_id".
::ffff:192.168.1.132 - - [11/Sep/2025:09:43:16 +0200] "POST /setup/ HTTP/1.1" 500 145 "http://192.168.1.128:12345/setup/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0"
::ffff:192.168.1.132 - - [11/Sep/2025:09:43:18 +0200] "GET /favicon.ico HTTP/1.1" 302 0 "http://192.168.1.128:12345/setup/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0"
::ffff:192.168.1.132 - - [11/Sep/2025:09:48:12 +0200] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0"
ThreadPoolExecutor-0_0 ERROR 2025-09-11 09:48:25,125 django.request Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/allauth/decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/allauth/account/views.py", line 99, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/allauth/account/mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/allauth/account/mixins.py", line 72, in get
    response = super().get(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/views/generic/edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
                                   ~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/allauth/account/views.py", line 126, in get_context_data
    site = get_current_site(self.request)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/sites/shortcuts.py", line 16, in get_current_site
    return Site.objects.get_current(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/sites/models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
`

**Comment by Harnish** [comment]
I just took a grab a the end because it looks like it is just missing file in staticfiles.json
```rver_url
    return staticfiles_storage.url(production_server_url)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
    raise ValueError(
        "Missing staticfiles manifest entry for '%s'" % clean_name
    )
ValueError: Missing staticfiles manifest entry for 'vue3/assets/main-CkTMHhTM.js'
```

```
grep main-CkTMHhTM staticfiles.json | wc -l
0
```

**Comment by foxbw** [comment]
I'm getting the exact same error as Harnish after installing version 2.2.0. Here are the last lines of the error message:

  ```
File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
    raise ValueError(
        "Missing staticfiles manifest entry for '%s'" % clean_name
    )
ValueError: Missing staticfiles manifest entry for 'vue3/assets/main-CkTMHhTM.js'
```

**Comment by vabene1111** [comment]
It would be very helpful if anyone would try what I asked in the message above and properly restart their contianer after this issue occurs? docker compose down and then docker compose up again. 

Also setting `DEBUG=1` and posting the logs during the boot script (server startup) would be very useful, otherwise I will not be able to get any farther with this issue.

**Comment by ChrisMichl** [comment]
I startet 2.1.1 with DEBUG=1 but unfortunatelly i cant reproduce the error anymore.

**Comment by vabene1111** [comment]
can you reproduce it without debug on 2.2.0?

**Comment by foxbw** [comment]
If I set the system to DEBUG = 1, everything works without error messages, and the web app is accessible. If I set the debug back to 0, the errors reappear, and the web app is unavailable. Tested with version 2.2.0

**Comment by vabene1111** [comment]
thank you for testing, now for the second part of the question: "the logs during the boot script (server startup) would be very useful"

**Comment by KartOMania** [comment]
Mine is a different error. sorry.

**Comment by foxbw** [comment]
Do you mean the protocol I can select in the Tandoor add-on? Or something else?

**Comment by EifX** [comment]
Hey @vabene1111 , I have the same issue as @foxbw or @ChrisMichl have mentioned. I upgraded from 1.5.34 to 2.0, 2.1 and 2.2 (step-wise)

Here my logs for `DEBUG=1`:

```
root@ubuntu:/opt/tandoor# docker compose logs
db_recipes-1     | 
db_recipes-1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_recipes-1     | 
db_recipes-1     | 2025-09-16 21:55:31.024 CEST [1] LOG:  starting PostgreSQL 16.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
db_recipes-1     | 2025-09-16 21:55:31.024 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_recipes-1     | 2025-09-16 21:55:31.025 CEST [1] LOG:  listening on IPv6 address "::", port 5432
web_recipes-1    | Checking configuration...
web_recipes-1    | Waiting for database to be ready...
web_recipes-1    | Database is ready
web_recipes-1    | Migrating database
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | Operations to perform:
db_recipes-1     | 2025-09-16 21:55:31.027 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
nginx_recipes-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
web_recipes-1    |   Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, mfa, oauth2_provider, sessions, sites, socialaccount, usersessions
nginx_recipes-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_recipes-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_recipes-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_recipes-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx_recipes-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
web_recipes-1    | Running migrations:
web_recipes-1    |   No migrations to apply.
web_recipes-1    |   Your models in app(s): 'cookbook' have changes that are not yet reflected in a migration, and so won't be applied.
web_recipes-1    |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
web_recipes-1    | Collecting static files, this may take a while...
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | 
web_recipes-1    | 0 static files copied to '/opt/recipes/staticfiles', 781 unmodified, 1636 post-processed.
web_recipes-1    | Done
web_recipes-1    | Starting nginx
web_recipes-1    | Starting gunicorn
web_recipes-1    | [2025-09-16 21:55:41 +0200] [7] [INFO] Starting gunicorn 23.0.0
web_recipes-1    | [2025-09-16 21:55:41 +0200] [7] [INFO] Listening at: http://[::]:8080 (7)
web_recipes-1    | [2025-09-16 21:55:41 +0200] [7] [INFO] Using worker: gthread
web_recipes-1    | [2025-09-16 21:55:41 +0200] [31] [INFO] Booting worker with pid: 31
web_recipes-1    | [2025-09-16 21:55:42 +0200] [32] [INFO] Booting worker with pid: 32
web_recipes-1    | [2025-09-16 21:55:42 +0200] [33] [INFO] Booting worker with pid: 33
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | Running django-vite in production mode (no HMR)
```

And for `DEBUG=0`:

```
root@ubuntu:/opt/tandoor# docker compose logs
nginx_recipes-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
web_recipes-1    | Checking configuration...
web_recipes-1    | Waiting for database to be ready...
web_recipes-1    | Database is ready
web_recipes-1    | Migrating database
web_recipes-1    | Running django-vite in production mode (no HMR)
nginx_recipes-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_recipes-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_recipes-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_recipes-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx_recipes-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_recipes-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
db_recipes-1     | 
db_recipes-1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_recipes-1     | 
db_recipes-1     | 2025-09-16 22:02:14.088 CEST [1] LOG:  starting PostgreSQL 16.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
db_recipes-1     | 2025-09-16 22:02:14.088 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_recipes-1     | 2025-09-16 22:02:14.088 CEST [1] LOG:  listening on IPv6 address "::", port 5432
db_recipes-1     | 2025-09-16 22:02:14.091 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_recipes-1     | 2025-09-16 22:02:14.109 CEST [29] LOG:  database system was shut down at 2025-09-16 22:02:09 CEST
db_recipes-1     | 2025-09-16 22:02:14.123 CEST [1] LOG:  database system is ready to accept connections
nginx_recipes-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: using the "epoll" event method
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: nginx/1.29.1
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: built by gcc 14.2.0 (Alpine 14.2.0) 
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: OS: Linux 6.8.0-71-generic
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
web_recipes-1    | Operations to perform:
web_recipes-1    |   Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, mfa, oauth2_provider, sessions, sites, socialaccount, usersessions
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: start worker processes
web_recipes-1    | Running migrations:
web_recipes-1    |   No migrations to apply.
web_recipes-1    |   Your models in app(s): 'cookbook' have changes that are not yet reflected in a migration, and so won't be applied.
web_recipes-1    |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
web_recipes-1    | Collecting static files, this may take a while...
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | 
web_recipes-1    | 0 static files copied to '/opt/recipes/staticfiles', 781 unmodified, 1636 post-processed.
web_recipes-1    | Done
web_recipes-1    | Starting nginx
web_recipes-1    | Starting gunicorn
web_recipes-1    | [2025-09-16 22:02:26 +0200] [8] [INFO] Starting gunicorn 23.0.0
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: start worker process 20
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: start worker process 21
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: start worker process 22
nginx_recipes-1  | 2025/09/16 22:02:14 [notice] 1#1: start worker process 23
web_recipes-1    | [2025-09-16 22:02:26 +0200] [8] [INFO] Listening at: http://[::]:8080 (8)
web_recipes-1    | [2025-09-16 22:02:26 +0200] [8] [INFO] Using worker: gthread
web_recipes-1    | [2025-09-16 22:02:26 +0200] [32] [INFO] Booting worker with pid: 32
web_recipes-1    | [2025-09-16 22:02:26 +0200] [33] [INFO] Booting worker with pid: 33
web_recipes-1    | [2025-09-16 22:02:26 +0200] [34] [INFO] Booting worker with pid: 34
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | ThreadPoolExecutor-0_0 ERROR 2025-09-16 22:03:18,622 django.request Internal Server Error: /
web_recipes-1    | Traceback (most recent call last):
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
web_recipes-1    |     response = get_response(request)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
web_recipes-1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_recipes-1    |   File "/opt/recipes/cookbook/views/views.py", line 46, in index
web_recipes-1    |     return render(request, 'frontend/tandoor.html', {})
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/shortcuts.py", line 24, in render
web_recipes-1    |     content = loader.render_to_string(template_name, context, request, using=using)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
web_recipes-1    |     return template.render(context, request)
web_recipes-1    |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 61, in render
web_recipes-1    |     return self.template.render(context)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 175, in render
web_recipes-1    |     return self._render(context)
web_recipes-1    |            ~~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 167, in _render
web_recipes-1    |     return self.nodelist.render(context)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 1005, in render
web_recipes-1    |     return SafeString("".join([node.render_annotated(context) for node in self]))
web_recipes-1    |                                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 966, in render_annotated
web_recipes-1    |     return self.render(context)
web_recipes-1    |            ~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/library.py", line 237, in render
web_recipes-1    |     output = self.func(*resolved_args, **resolved_kwargs)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/utils/safestring.py", line 53, in wrapper
web_recipes-1    |     return safety_marker(func(*args, **kwargs))
web_recipes-1    |                          ~~~~^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/templatetags/django_vite.py", line 67, in vite_asset
web_recipes-1    |     return DjangoViteAssetLoader.instance().generate_vite_asset(path, app, **kwargs)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 818, in generate_vite_asset
web_recipes-1    |     return app_client.generate_vite_asset(path, **kwargs)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 328, in generate_vite_asset
web_recipes-1    |     tags.extend(self._load_css_files_of_asset(path, attrs=kwargs))
web_recipes-1    |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 434, in _load_css_files_of_asset
web_recipes-1    |     return self._generate_css_files_of_asset(
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
web_recipes-1    |         path,
web_recipes-1    |         ^^^^^
web_recipes-1    |         tag_generator=TagGenerator.stylesheet,
web_recipes-1    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |         attrs=attrs,
web_recipes-1    |         ^^^^^^^^^^^^
web_recipes-1    |     ).tags
web_recipes-1    |     ^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 497, in _generate_css_files_of_asset
web_recipes-1    |     url = self.get_production_server_url(css_path)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 286, in get_production_server_url
web_recipes-1    |     return staticfiles_storage.url(production_server_url)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
web_recipes-1    |     return self._url(self.stored_name, name, force)
web_recipes-1    |            ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
web_recipes-1    |     hashed_name = hashed_name_func(*args)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
web_recipes-1    |     raise ValueError(
web_recipes-1    |         "Missing staticfiles manifest entry for '%s'" % clean_name
web_recipes-1    |     )
web_recipes-1    | ValueError: Missing staticfiles manifest entry for 'vue3/assets/main-C3CI9azl.css'
```

**Comment by vabene1111** [comment]
thank you for the logs, this is even stranger, the collect static runs just fine which should collect and setup all staticfiles as needed. Right after it appears to try to access a missing file. 

I have no idea why this happens, probably something stupid somewere, given that I cannot reproduce it its going to be hard to fix but I will look into this further. 

Another thing I need to check is why its showing unmigrated model changes in your log

**Comment by EifX** [comment]
Hum... some more insights into the problem. Everything is fine if I start with a clean browser without cookies and so on. Then everything seems to be fine. AFTER I logged in into tandoor, the error occurs. Again the logs, including the browser-calls:

```
web_recipes-1    | [2025-09-17 21:37:15 +0200] [6] [INFO] Starting gunicorn 23.0.0
web_recipes-1    | [2025-09-17 21:37:15 +0200] [6] [INFO] Listening at: http://[::]:8080 (6)
web_recipes-1    | [2025-09-17 21:37:15 +0200] [6] [INFO] Using worker: gthread
web_recipes-1    | [2025-09-17 21:37:15 +0200] [36] [INFO] Booting worker with pid: 36
web_recipes-1    | [2025-09-17 21:37:15 +0200] [37] [INFO] Booting worker with pid: 37
web_recipes-1    | [2025-09-17 21:37:15 +0200] [38] [INFO] Booting worker with pid: 38
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | Running django-vite in production mode (no HMR)
web_recipes-1    | Running django-vite in production mode (no HMR)
db_recipes-1     | 2025-09-17 21:37:04.533 CEST [1] LOG:  database system is ready to accept connections
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:37:51 +0200] "GET /search/ HTTP/1.0" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:37:52 +0200] "GET /accounts/login/?next=/search/ HTTP/1.0" 200 5223 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:37:52 +0200] "GET /static/css/app.min.050361699392.css HTTP/1.0" 200 0 "https://tandoor.example.com/accounts/login/?next=/search/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:37:52 +0200] "GET /static/themes/tandoor.min.e62f1984b5e4.css HTTP/1.0" 200 0 "https://tandoor.example.com/accounts/login/?next=/search/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:37:52 +0200] "GET /static/js/popper.min.8156384b48c7.js HTTP/1.0" 200 0 "https://tandoor.example.com/accounts/login/?next=/search/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:37:52 +0200] "GET /static/js/jquery-3.5.1.min.dc5e7f18c8d3.js HTTP/1.0" 200 0 "https://tandoor.example.com/accounts/login/?next=/search/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:37:52 +0200] "GET /service-worker.js HTTP/1.0" 200 40723 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:38:19 +0200] "POST /accounts/login/ HTTP/1.0" 302 0 "https://tandoor.example.com/accounts/login/?next=/search/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
web_recipes-1    | ThreadPoolExecutor-0_0 ERROR 2025-09-17 21:38:19,348 django.request Internal Server Error: /search/
web_recipes-1    | Traceback (most recent call last):
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
web_recipes-1    |     response = get_response(request)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
web_recipes-1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_recipes-1    |   File "/opt/recipes/cookbook/views/views.py", line 46, in index
web_recipes-1    |     return render(request, 'frontend/tandoor.html', {})
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/shortcuts.py", line 24, in render
web_recipes-1    |     content = loader.render_to_string(template_name, context, request, using=using)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
web_recipes-1    |     return template.render(context, request)
web_recipes-1    |            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 61, in render
web_recipes-1    |     return self.template.render(context)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 175, in render
web_recipes-1    |     return self._render(context)
web_recipes-1    |            ~~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 167, in _render
web_recipes-1    |     return self.nodelist.render(context)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 1005, in render
web_recipes-1    |     return SafeString("".join([node.render_annotated(context) for node in self]))
web_recipes-1    |                                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/base.py", line 966, in render_annotated
web_recipes-1    |     return self.render(context)
web_recipes-1    |            ~~~~~~~~~~~^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/template/library.py", line 237, in render
web_recipes-1    |     output = self.func(*resolved_args, **resolved_kwargs)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/utils/safestring.py", line 53, in wrapper
web_recipes-1    |     return safety_marker(func(*args, **kwargs))
web_recipes-1    |                          ~~~~^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/templatetags/django_vite.py", line 67, in vite_asset
web_recipes-1    |     return DjangoViteAssetLoader.instance().generate_vite_asset(path, app, **kwargs)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 818, in generate_vite_asset
web_recipes-1    |     return app_client.generate_vite_asset(path, **kwargs)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 328, in generate_vite_asset
web_recipes-1    |     tags.extend(self._load_css_files_of_asset(path, attrs=kwargs))
web_recipes-1    |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 434, in _load_css_files_of_asset
web_recipes-1    |     return self._generate_css_files_of_asset(
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
web_recipes-1    |         path,
web_recipes-1    |         ^^^^^
web_recipes-1    |         tag_generator=TagGenerator.stylesheet,
web_recipes-1    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |         attrs=attrs,
web_recipes-1    |         ^^^^^^^^^^^^
web_recipes-1    |     ).tags
web_recipes-1    |     ^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 497, in _generate_css_files_of_asset
web_recipes-1    |     url = self.get_production_server_url(css_path)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django_vite/core/asset_loader.py", line 286, in get_production_server_url
web_recipes-1    |     return staticfiles_storage.url(production_server_url)
web_recipes-1    |            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
web_recipes-1    |     return self._url(self.stored_name, name, force)
web_recipes-1    |            ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
web_recipes-1    |     hashed_name = hashed_name_func(*args)
web_recipes-1    |   File "/opt/recipes/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
web_recipes-1    |     raise ValueError(
web_recipes-1    |         "Missing staticfiles manifest entry for '%s'" % clean_name
web_recipes-1    |     )
web_recipes-1    | ValueError: Missing staticfiles manifest entry for 'vue3/assets/main-C3CI9azl.css'
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:38:19 +0200] "GET /search/ HTTP/1.0" 500 145 "https://tandoor.example.com/accounts/login/?next=/search/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
web_recipes-1    | ::ffff:172.18.0.4 - - [17/Sep/2025:21:38:19 +0200] "GET /service-worker.js HTTP/1.0" 200 40723 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"

```

I tried to look deeper into the container. I don't have any knowledge about the technology you use - but I try to help... :D

What I see is, that within the `staticfiles/staticfiles.json` only this 4 files exist with the filename "main":

- vue3/assets/main-CLDT5N66.js
- vue3/assets/main-CLDT5N66.71e1c34d489e.js
- vue3/assets/main-BVoCCfzU.css
- vue3/assets/main-BVoCCfzU.acbe338fa6a9.css

This did not change if I turn `DEBUG=0` or `DEBUG=1`.

If I look into /opt/recipes/staticfiles/vue3/assets, I see that the following files are existing:

```
main-BVoCCfzU.acbe338fa6a9.css
main-BVoCCfzU.acbe338fa6a9.css.gz
main-BVoCCfzU.css
main-BVoCCfzU.css.gz
main-C3CI9azl.089786f5fbc0.css
main-C3CI9azl.089786f5fbc0.css.gz
main-C3CI9azl.css
main-C3CI9azl.css.gz
main-CLDT5N66.71e1c34d489e.js
main-CLDT5N66.71e1c34d489e.js.gz
main-CLDT5N66.js
main-CLDT5N66.js.gz
main-CkTMHhTM.31971cea4057.js
main-CkTMHhTM.31971cea4057.js.gz
main-CkTMHhTM.js
main-CkTMHhTM.js.gz
main-DSgyAKk9.1d6a406aa3cc.js
main-DSgyAKk9.1d6a406aa3cc.js.gz
main-DSgyAKk9.js
main-DSgyAKk9.js.gz
```

So everything should be there - but is not find because it's missing in the staticfiles.json?

ps: I believe that the error occures within the change from v2.0 to 2.1. At v2.0 everything was working as expected.

**Comment by vabene1111** [comment]
ok so i have an idea. Can anyone with this issue send post or send me the contents of two files in the /opt/recipes/ in their docker container

1. /opt/recipe/cookbook/static/vue3/manifest.json
2. /opt/recipes/staticfiles/vue3/manifest.json

after that you can try fixing the issue by running this command inside the container and then restarting it `collectstatic --clear --no-input`

Note for myself:
Fix might also be pointing django vite directly to the manifest in the static folder instead of the collected static files by using 
```
"manifest_path": os.path.join(BASE_DIR, 'cookbook/static/vue3/manifest.json'),
```
altough I would need to review if this causes any more issues than already for uncollected or outdated staticfiles 🤔

**Comment by EifX** [comment]
Hey,

I sent you also an E-Mail with the attached files, which you're requested. I hope I could help.

Were I should execute the `collectstatic` prompt? I don't have such command:

```
/opt/recipes # collectstatic --clear --no-input
sh: collectstatic: not found
``` 

[cookbook.manifest.json](https://github.com/user-attachments/files/22500160/cookbook.manifest.json)
[staticfiles.manifest.json](https://github.com/user-attachments/files/22500161/staticfiles.manifest.json)

**Comment by EifX** [comment]
Ehm ... I updated to the newest version (from 2.2.0 to 2.2.3). I don't know what you have done meanwhile - but the bug went away from my point of view. Everything is looking fine.

I also tested logout and logon.

**Comment by vabene1111** [comment]
Sorry for not being clear about this. Collectstatic is one of djangos management commands. You execute it from outside the container by running

```shell
docker compose run <container name> python3 manage.py collectstatic --noinput --clear
```

or inside using 
```shell
python3 manage.py collectstatic --noinput --clear
```

the files you send me confirm my suspicion. The issues seems to be that the manifest.json file in the vue build output dir is not correctly transferred to the staticfiles directory form where django vite takes the data. I do not know why this happens because I would expect djangos collect static command to work flawlessly but maybe its a timing issue of something with certain setups or similar. This would also explain why this sometimes happens and sometimes not depending on the version/update.

I would like to confirm this theory by someone executing the above command but I have also implemented a fix to change django vite to not use the collected but the source static files for the manifest access which should fix it as well.

**Comment by EifX** [comment]
I downgraded from 2.2.3 back to 2.2.0 to help you - but I've got only the following output, when I execute the command within the container:

```
/opt/recipes # python3 manage.py collectstatic --noinput --clear
Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 10, in <module>
    raise ImportError(
    ...<3 lines>...
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

I tried to install django via pip3, but more and more error messages came up (missing modules dotenv and psycopg). What else can I do to help you?

**Comment by vabene1111** [comment]
ah, sorry, the problem is that the venv isn't activated. Do you reliably get the error after the downgrade again?

before running the command you need to run `source venv/bin/activate` which should prepend a (venv) text to your console line

```
/opt/recipes # source venv/bin/activate
(venv) /opt/recipes 
```
then you can run collectstaitc

**Comment by EifX** [comment]
Thanks for the help. Jepp, the error still persist after downgrade. I was able to execute the commands. I attached the output in `collectstatic-output.txt`.

[collectstatic-output.txt](https://github.com/user-attachments/files/22518625/collectstatic-output.txt)

After execution, I stopped and restarted the container with `docker compose down && docker compose up -d`.

The error did not appear again. Version 2.2.0 is now usable for me. Seems that your assumption is correct 😄 👍

**Comment by vabene1111** [comment]
awesome, glad this weird issue is resolved. I am still pretty confused that this happend in the first place but I implemented two strategies to resolve this for the future so this should hopefully not happen again.

Thanks for your and everyone elses help in debugging this.
